# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Check for Go dependency updates every day
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "go"
    open-pull-requests-limit: 10

  # Check for GitHub Actions updates every day
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
